### ISSUE TITLE
Typo in function name

### ISSUE THREAD

**Issue by sbvoxel** [rivo/sessions#1]
Hi. This looks like a quality library. I just wanted to let you know that the function 'generateSesssionID' has three 's' in Session which seems like a typo. I noticed because I was grepping for its use and nothing popped up, including its definition.

I wouldn't bother if this were a typo in a comment but it's the name a pretty important function :)

Feel free to delete the issue after you've noticed. This is just a 'DM' in 'Issue' form.

**Comment by rivo** [comment]
Thank you. Do you want to submit a pull request for this?

**Comment by sbvoxel** [comment]
Done. I didn't know how to do that when I opened the issue.

**Comment by rivo** [comment]
Well, there you go! You just contributed code to an open source project. ;-)
